### ISSUE TITLE
Incorrect parsing of PURLs begining with `pkg://`

### ISSUE THREAD

**Issue by matt-phylum** [package-url/packageurl-js#58] opened 2023-11-08 16:49 UTC
The PURL test suite contains the PURL `pkg://maven/org.apache.commons/io` which is supposed to parse as a namespace of `org.apache.commons` and a name of `io`, but packageurl-js parses it as having no namespace. The namespace just disappears. It doesn't become part of the name.

**Comment by aniruth37** [comment] 2023-12-06 09:41
Raised https://github.com/package-url/packageurl-js/pull/62 to fix this

**Comment by jdalton** [comment] 2024-05-16 12:06
Cannot reproduce bug given the example above:
https://github.com/package-url/packageurl-js/pull/62#issuecomment-2115067509

**Comment by matt-phylum** [comment] 2024-05-16 12:45
This is still reproducible with the given example.

**Comment by jdalton** [comment] 2024-05-16 17:44
Ah, my bad. @matt-phylum you are correct.

**Comment by jdalton** [comment] 2024-08-13 16:09
Fixed in master branch.

**Closed as completed by jdalton** 2024-08-13 16:09 UTC
